# This is the NC-SIM(R) probe command file used in AMS-ADE integration
if { [info exists ::env(AMS_RESULTS_DIR) ] } { set AMS_RESULTS_DIR $env(AMS_RESULTS_DIR)} else {set AMS_RESULTS_DIR "../psf"}
database -open ams_database -shm -into ${AMS_RESULTS_DIR} -default
database -open waves -into resultDirName.shm -default 
probe -create -database waves -all -depth -all
probe -create -emptyok -database ams_database {Top_Recall_Only.tb_jk_clk}
probe -create -emptyok -database ams_database {Top_Recall_Only.tb_switch_en}
probe -create -emptyok -database ams_database {Top_Recall_Only.tb_x_out_res[1]}
probe -create -emptyok -database ams_database {Top_Recall_Only.tb_en_lu_x[1]}
probe -create -emptyok -database ams_database {Top_Recall_Only.tb_x_out_res[2]}
probe -create -emptyok -database ams_database {Top_Recall_Only.tb_en_lu_x[2]}
probe -create -emptyok -database ams_database {Top_Recall_Only.tb_x_out_res[3]}
probe -create -emptyok -database ams_database {Top_Recall_Only.tb_en_lu_x[3]}
probe -create -emptyok -database ams_database {Top_Recall_Only.tb_x_out_res[4]}
probe -create -emptyok -database ams_database {Top_Recall_Only.tb_en_lu_x[4]}
probe -create -emptyok -database ams_database {Top_Recall_Only.tb_x_out_res[5]}
probe -create -emptyok -database ams_database {Top_Recall_Only.tb_en_lu_x[5]}
probe -create -emptyok -database ams_database {Top_Recall_Only.tb_x_out_res[6]}
probe -create -emptyok -database ams_database {Top_Recall_Only.tb_en_lu_x[6]}
probe -create -emptyok -database ams_database {Top_Recall_Only.tb_x_out_res[7]}
probe -create -emptyok -database ams_database {Top_Recall_Only.tb_en_lu_x[7]}
probe -create -emptyok -database ams_database {Top_Recall_Only.tb_x_out_res[8]}
probe -create -emptyok -database ams_database {Top_Recall_Only.tb_en_lu_x[8]}
probe -create -emptyok -database ams_database {Top_Recall_Only.tb_x_out_res[9]}
probe -create -emptyok -database ams_database {Top_Recall_Only.tb_en_lu_x[9]}
probe -create -emptyok -database ams_database {Top_Recall_Only.tb_x_out_res[10]}
probe -create -emptyok -database ams_database {Top_Recall_Only.tb_en_lu_x[10]}
probe -create -emptyok -database ams_database {Top_Recall_Only.tb_x_out_res[11]}
probe -create -emptyok -database ams_database {Top_Recall_Only.tb_en_lu_x[11]}
probe -create -emptyok -database ams_database {Top_Recall_Only.tb_x_out_res[12]}
probe -create -emptyok -database ams_database {Top_Recall_Only.tb_en_lu_x[12]}
probe -create -emptyok -database ams_database {Top_Recall_Only.tb_x_out_res[13]}
probe -create -emptyok -database ams_database {Top_Recall_Only.tb_en_lu_x[13]}
probe -create -emptyok -database ams_database {Top_Recall_Only.tb_x_out_res[14]}
probe -create -emptyok -database ams_database {Top_Recall_Only.tb_en_lu_x[14]}
probe -create -emptyok -database ams_database {Top_Recall_Only.tb_x_out_res[15]}
probe -create -emptyok -database ams_database {Top_Recall_Only.tb_en_lu_x[15]}
probe -create -emptyok -database ams_database {Top_Recall_Only.tb_x_out_res[16]}
probe -create -emptyok -database ams_database {Top_Recall_Only.tb_en_lu_x[16]}
probe -create -emptyok -database ams_database {Top_Recall_Only.tb_x_out_res[17]}
probe -create -emptyok -database ams_database {Top_Recall_Only.tb_en_lu_x[17]}
probe -create -emptyok -database ams_database {Top_Recall_Only.tb_x_out_res[18]}
probe -create -emptyok -database ams_database {Top_Recall_Only.tb_en_lu_x[18]}
probe -create -emptyok -database ams_database {Top_Recall_Only.tb_x_out_res[19]}
probe -create -emptyok -database ams_database {Top_Recall_Only.tb_en_lu_x[19]}
probe -create -emptyok -database ams_database {Top_Recall_Only.tb_x_out_res[20]}
probe -create -emptyok -database ams_database {Top_Recall_Only.tb_en_lu_x[20]}
probe -create -emptyok -database ams_database {Top_Recall_Only.tb_x_out_res[21]}
probe -create -emptyok -database ams_database {Top_Recall_Only.tb_en_lu_x[21]}
probe -create -emptyok -database ams_database {Top_Recall_Only.tb_x_out_res[22]}
probe -create -emptyok -database ams_database {Top_Recall_Only.tb_en_lu_x[22]}
probe -create -emptyok -database ams_database {Top_Recall_Only.tb_x_out_res[23]}
probe -create -emptyok -database ams_database {Top_Recall_Only.tb_en_lu_x[23]}
probe -create -emptyok -database ams_database {Top_Recall_Only.tb_x_out_res[24]}
probe -create -emptyok -database ams_database {Top_Recall_Only.tb_en_lu_x[24]}
probe -create -emptyok -database ams_database {Top_Recall_Only.tb_y_in[1]}
probe -create -emptyok -database ams_database {Top_Recall_Only.tb_en_lu_y[1]}
probe -create -emptyok -database ams_database {Top_Recall_Only.tb_y_in[2]}
probe -create -emptyok -database ams_database {Top_Recall_Only.tb_en_lu_y[2]}
probe -create -emptyok -database ams_database {Top_Recall_Only.tb_y_in[3]}
probe -create -emptyok -database ams_database {Top_Recall_Only.tb_en_lu_y[3]}
probe -create -emptyok -database ams_database {Top_Recall_Only.tb_y_in[4]}
probe -create -emptyok -database ams_database {Top_Recall_Only.tb_en_lu_y[4]}
probe -create -emptyok -database ams_database {Top_Recall_Only.tb_y_in[5]}
probe -create -emptyok -database ams_database {Top_Recall_Only.tb_en_lu_y[5]}
probe -create -emptyok -database ams_database {Top_Recall_Only.tb_y_in[6]}
probe -create -emptyok -database ams_database {Top_Recall_Only.tb_en_lu_y[6]}
probe -create -emptyok -database ams_database {Top_Recall_Only.tb_y_in[7]}
probe -create -emptyok -database ams_database {Top_Recall_Only.tb_en_lu_y[7]}
probe -create -emptyok -database ams_database {Top_Recall_Only.tb_y_in[8]}
probe -create -emptyok -database ams_database {Top_Recall_Only.tb_en_lu_y[8]}
probe -create -emptyok -database ams_database {Top_Recall_Only.tb_y_in[9]}
probe -create -emptyok -database ams_database {Top_Recall_Only.tb_en_lu_y[9]}
probe -create -emptyok -database ams_database {Top_Recall_Only.tb_y_in[10]}
probe -create -emptyok -database ams_database {Top_Recall_Only.tb_en_lu_y[10]}
probe -create -emptyok -database ams_database {Top_Recall_Only.tb_y_in[11]}
probe -create -emptyok -database ams_database {Top_Recall_Only.tb_en_lu_y[11]}
probe -create -emptyok -database ams_database {Top_Recall_Only.tb_y_in[12]}
probe -create -emptyok -database ams_database {Top_Recall_Only.tb_en_lu_y[12]}
probe -create -emptyok -database ams_database {Top_Recall_Only.tb_y_in[13]}
probe -create -emptyok -database ams_database {Top_Recall_Only.tb_en_lu_y[13]}
probe -create -emptyok -database ams_database {Top_Recall_Only.tb_y_in[14]}
probe -create -emptyok -database ams_database {Top_Recall_Only.tb_en_lu_y[14]}
probe -create -emptyok -database ams_database {Top_Recall_Only.tb_y_in[15]}
probe -create -emptyok -database ams_database {Top_Recall_Only.tb_en_lu_y[15]}
probe -create -emptyok -database ams_database {Top_Recall_Only.tb_y_in[16]}
probe -create -emptyok -database ams_database {Top_Recall_Only.tb_en_lu_y[16]}
probe -create -emptyok -database ams_database {Top_Recall_Only.tb_y_in[17]}
probe -create -emptyok -database ams_database {Top_Recall_Only.tb_en_lu_y[17]}
probe -create -emptyok -database ams_database {Top_Recall_Only.tb_y_in[18]}
probe -create -emptyok -database ams_database {Top_Recall_Only.tb_en_lu_y[18]}
probe -create -emptyok -database ams_database {Top_Recall_Only.tb_y_in[19]}
probe -create -emptyok -database ams_database {Top_Recall_Only.tb_en_lu_y[19]}
probe -create -emptyok -database ams_database {Top_Recall_Only.tb_y_in[20]}
probe -create -emptyok -database ams_database {Top_Recall_Only.tb_en_lu_y[20]}
probe -create -emptyok -database ams_database {Top_Recall_Only.tb_y_in[21]}
probe -create -emptyok -database ams_database {Top_Recall_Only.tb_en_lu_y[21]}
probe -create -emptyok -database ams_database {Top_Recall_Only.tb_y_in[22]}
probe -create -emptyok -database ams_database {Top_Recall_Only.tb_en_lu_y[22]}
probe -create -emptyok -database ams_database {Top_Recall_Only.tb_y_in[23]}
probe -create -emptyok -database ams_database {Top_Recall_Only.tb_en_lu_y[23]}
probe -create -emptyok -database ams_database {Top_Recall_Only.tb_y_in[24]}
probe -create -emptyok -database ams_database {Top_Recall_Only.tb_en_lu_y[24]}
